// Off-chain simulator for the ProofOps Compact contract, following the same pattern as
// the official midnightntwrk/example-counter CounterSimulator
// (contract/src/test/counter-simulator.ts): construct a Contract with witnesses, derive
// its initial state, then drive circuits through a CircuitContext - no wallet, node, or
// network required.
import {
  createCircuitContext,
  createConstructorContext,
  sampleContractAddress,
  type CircuitContext,
  type WitnessContext,
} from "@midnight-ntwrk/compact-runtime";
// Generated by `compact compile` from ../src/proofops.compact. Run `npm run contract:build`
// (from the repo root) before running these tests if ../dist is missing.
import { Contract, ledger, type Ledger, type Witnesses } from "../dist/contract/index.js";

export interface ProofOpsPrivateState {
  readonly responseTimeMinutes: bigint;
}

function createWitnesses(): Witnesses<ProofOpsPrivateState> {
  return {
    responseTimeMinutes(
      context: WitnessContext<Ledger, ProofOpsPrivateState>
    ): [ProofOpsPrivateState, bigint] {
      // The private response time is read from local test state only. It is returned to
      // the circuit as a witness value and is never written back into private state or
      // exposed on the ledger.
      return [context.privateState, context.privateState.responseTimeMinutes];
    },
  };
}

export class ProofOpsSimulator {
  readonly contract: Contract<ProofOpsPrivateState>;
  circuitContext: CircuitContext<ProofOpsPrivateState>;

  constructor(responseTimeMinutes: bigint) {
    this.contract = new Contract<ProofOpsPrivateState>(createWitnesses());
    const { currentPrivateState, currentContractState, currentZswapLocalState } =
      this.contract.initialState(createConstructorContext({ responseTimeMinutes }, "0".repeat(64)));
    this.circuitContext = createCircuitContext(
      sampleContractAddress(),
      currentZswapLocalState,
      currentContractState,
      currentPrivateState
    );
  }

  getLedger(): Ledger {
    return ledger(this.circuitContext.currentQueryContext.state);
  }

  /** Throws if the private response time exceeds limitMinutes - the contract rejects the proof. */
  submitReceipt(incidentIdHash: Uint8Array, evidenceCommitment: Uint8Array, limitMinutes: bigint): Ledger {
    this.circuitContext = this.contract.impureCircuits.submitReceipt(
      this.circuitContext,
      incidentIdHash,
      evidenceCommitment,
      limitMinutes
    ).context;
    return this.getLedger();
  }

  getReceiptCount(): bigint {
    const result = this.contract.impureCircuits.getReceiptCount(this.circuitContext);
    this.circuitContext = result.context;
    return result.result;
  }
}
